version: '3'
services:
  t1-dashboard:
    build: .
    ports:
      - "1337:1337"
    depends_on:
      - timescaledb
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
  timescaledb:
    image: timescale/timescaledb:latest-pg10
    ports:
      - "5432:5432"

